name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          run-install: true

      - name: Install semantic-release
        run: |
          vp add \
            semantic-release \
            @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/github \
            @semantic-release/npm \
            conventional-changelog-conventionalcommits \
            -- --no-save

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: vpx semantic-release
